server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/comment?useSSL=false&serverTimezone=UTC
    username: root
    password: Pooja@151
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true